// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PluginInitParameters struct {

	// (Map of String) Plugin config.
	// Plugin config.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// (String) The slug of the organization the project belongs to.
	// The slug of the organization the project belongs to.
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (String) Plugin ID.
	// Plugin ID.
	Plugin *string `json:"plugin,omitempty" tf:"plugin,omitempty"`

	// (String) The slug of the project to create the plugin for.
	// The slug of the project to create the plugin for.
	// +crossplane:generate:reference:type=github.com/justtrack/provider-sentry/apis/sentry/v1alpha1.Project
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in sentry to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v1.Reference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in sentry to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v1.Selector `json:"projectSelector,omitempty" tf:"-"`
}

type PluginObservation struct {

	// (Map of String) Plugin config.
	// Plugin config.
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The slug of the organization the project belongs to.
	// The slug of the organization the project belongs to.
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (String) Plugin ID.
	// Plugin ID.
	Plugin *string `json:"plugin,omitempty" tf:"plugin,omitempty"`

	// (String) The slug of the project to create the plugin for.
	// The slug of the project to create the plugin for.
	Project *string `json:"project,omitempty" tf:"project,omitempty"`
}

type PluginParameters struct {

	// (Map of String) Plugin config.
	// Plugin config.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Config map[string]*string `json:"config,omitempty" tf:"config,omitempty"`

	// (String) The slug of the organization the project belongs to.
	// The slug of the organization the project belongs to.
	// +kubebuilder:validation:Optional
	Organization *string `json:"organization,omitempty" tf:"organization,omitempty"`

	// (String) Plugin ID.
	// Plugin ID.
	// +kubebuilder:validation:Optional
	Plugin *string `json:"plugin,omitempty" tf:"plugin,omitempty"`

	// (String) The slug of the project to create the plugin for.
	// The slug of the project to create the plugin for.
	// +crossplane:generate:reference:type=github.com/justtrack/provider-sentry/apis/sentry/v1alpha1.Project
	// +kubebuilder:validation:Optional
	Project *string `json:"project,omitempty" tf:"project,omitempty"`

	// Reference to a Project in sentry to populate project.
	// +kubebuilder:validation:Optional
	ProjectRef *v1.Reference `json:"projectRef,omitempty" tf:"-"`

	// Selector for a Project in sentry to populate project.
	// +kubebuilder:validation:Optional
	ProjectSelector *v1.Selector `json:"projectSelector,omitempty" tf:"-"`
}

// PluginSpec defines the desired state of Plugin
type PluginSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PluginParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PluginInitParameters `json:"initProvider,omitempty"`
}

// PluginStatus defines the observed state of Plugin.
type PluginStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PluginObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Plugin is the Schema for the Plugins API. Sentry Plugin resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,sentry}
type Plugin struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.organization) || (has(self.initProvider) && has(self.initProvider.organization))",message="spec.forProvider.organization is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.plugin) || (has(self.initProvider) && has(self.initProvider.plugin))",message="spec.forProvider.plugin is a required parameter"
	Spec   PluginSpec   `json:"spec"`
	Status PluginStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PluginList contains a list of Plugins
type PluginList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Plugin `json:"items"`
}

// Repository type metadata.
var (
	Plugin_Kind             = "Plugin"
	Plugin_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Plugin_Kind}.String()
	Plugin_KindAPIVersion   = Plugin_Kind + "." + CRDGroupVersion.String()
	Plugin_GroupVersionKind = CRDGroupVersion.WithKind(Plugin_Kind)
)

func init() {
	SchemeBuilder.Register(&Plugin{}, &PluginList{})
}
